routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group([
    'middleware' => ['auth', 'can:use-site'],
], function () {

    //home (&event)
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/mail', 'HomeController@mail')->name('home.mail');
//    Route::get('/{year}/{month}/{day}', 'HomeController@index')->name('home');


    Route::resource('candidate', 'Candidate\CandidateController');
    Route::group([
            'prefix' => 'candidate',
            'as' => 'candidate.',
            'namespace' => 'Candidate',
        ],
        function () {

            Route::post('change-status/{candidate}/{status}', 'CandidateController@changeStatus')->name('changeStatus');
            Route::get('create-candidate-record/{user}', 'CandidateController@createCandidateRecord')->name('createCandidateRecord');
            Route::post('store-candidate-record/{user}', 'CandidateController@storeCandidateRecord')->name('storeCandidateRecord');
        }
    );

    Route::resource('user', 'User\UserController');
    Route::group([
        'prefix' => 'user',
        'as' => 'user.',
        'namespace' => 'User',
    ],
        function () {
            Route::post('change-status/{user}/{status}', 'UserController@changeStatus')->name('changeStatus');
        }
    );

    Route::resource('vacancy', 'VacancyController');

    Route::group([
        'prefix' => 'data',
        'as' => 'data.',
        'namespace' => 'Data',
    ],
        function () {
            Route::resource('currency', 'CurrencyController');
            Route::resource('city', 'CityController');
            Route::resource('position', 'PositionController');
            Route::resource('company', 'CompanyController');
        }
    );
/*
 |------------------------------------------------------------------------
 | Interviews
 |------------------------------------------------------------------------
*/
    Route::resource('interview', 'InterviewController');
/*
|------------------------------------------------------------------------
| Events & Calendar
|------------------------------------------------------------------------
*/

//    Route::group([
//        'prefix' => 'event',
//        'as' => 'event',
//        'namespace' => 'Event',
//    ],
//
//        function (){
//            Route::resource('calendar', 'EventController@calendar');
//        }
//    );

    Route::any('calendar', 'Event\EventController@index')->name('calendar.index');
    Route::any('calendar/create', 'Event\EventController@create')->name('calendar.create');
    Route::any('calendar/add', 'Event\EventController@add')->name('calendar.add');
});

app/Http/Controllers/User/UserController.php
<?php
namespace App\Http\Controllers\User;

use App\Entities\Candidate;
use App\Entities\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateRequest;
use App\Http\Requests\User\UpdateRequest;
use App\Services\User\UserService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Input;

/**
 * Class UserController
 */
class UserController extends Controller
{
    /**
     * @var UserService
     */
    private $service;

    /**
     * UserController constructor.
     * @param UserService $service
     */
    public function __construct(UserService $service)
    {
        $this->service = $service;
        $this->middleware('can:manage-users')->only(['changeStatus', 'destroy']);
    }

    /**
     * @return View
     */
    public function index(): View
    {
        $name = htmlspecialchars(Input::get('name'));
        if ( !empty($name) )
        {
            $users = User::workersStatus()
                ->lookEverywhere($name)
                ->orderBy('last_name', 'asc')
                ->paginate(10);
        }
        else
        {
            $users = User::workersStatus()
                ->orderBy('last_name', 'asc')
                ->paginate(10);
        }

        $statusesList = User::statusesList();

        return view('user.index',compact('users', 'statusesList'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return view('user.create');
    }

    /**
     * @param CreateRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        try {
            $this->service->createUser($request);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('user.index');
    }

    /**
     * @param User $user
     * @return View
     */
    public function edit(User $user): View
    {
        $this->checkAccess($user);
        return view('user.edit', compact('user'));
    }

    /**
     * @param UpdateRequest $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(UpdateRequest $request, User $user): RedirectResponse
    {
        $this->checkAccess($user);
        $this->service->updateUserInfo($request, $user);
        return redirect()->route('user.show', $user);
    }

    /**
     * @param User $user
     * @param int $status
     * @return RedirectResponse
     */
    public function changeStatus(User $user, int $status): RedirectResponse
    {
        try {
            $this->service->changeStatus($user, $status);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('user.show', $user->id);
    }

    /**
     * @param User $user
     * @return View
     */
    public function show(User $user): View
    {
        $statusesList = Candidate::statusesList();
        $userStatusesList = User::statusesList();
        return view('user.show', compact('user', 'statusesList', 'userStatusesList'));
    }

    /**
     * @param User $user
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();
        return redirect()->back();
    }

    /**
     * @param User $user
     */
    public function checkAccess(User $user): void
    {
        if (!Gate::allows('edit-user-data', $user)) {
            abort(403);
        }
    }

    public function search()
    {

    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Создание нового кандидата
                    <a href="{{ route('user.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
                        @csrf

                        @include('user._user-create-form-fields')

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Редактирование пользователя
                    <a href="{{ route('user.show', $user) }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.update', $user) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="first_name" class="col-form-label required">Имя</label>
                            <input id="first_name" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}" name="first_name" value="{{ old('first_name', $user->first_name) }}" required>
                            @if ($errors->has('first_name'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('first_name') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="last_name" class="col-form-label required">Фамилия</label>
                            <input id="last_name" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}" name="last_name" value="{{ old('last_name', $user->last_name) }}" required>
                            @if ($errors->has('last_name'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('last_name') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="second_name" class="col-form-label">Отчество</label>
                            <input id="second_name" class="form-control{{ $errors->has('second_name') ? ' is-invalid' : '' }}" name="second_name" value="{{ old('second_name', $user->second_name) }}">
                            @if ($errors->has('second_name'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('second_name') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-form-label required">E-Mail</label>
                            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email', $user->email) }}" required>
                            @if ($errors->has('email'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="socials" class="col-form-label">Ссылки на соцсети</label>
                            <textarea id="socials" class="form-control{{ $errors->has('socials') ? ' is-invalid' : '' }}" name="socials" rows="2">{{ old('socials', $user->socials) }}</textarea>
                            @if ($errors->has('socials'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('socials') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="education" class="col-form-label">Образование</label>
                            <textarea id="education" class="form-control{{ $errors->has('education') ? ' is-invalid' : '' }}" name="education" rows="2">{{ old('education', $user->education) }}</textarea>
                            @if ($errors->has('education'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('education') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            @if ($user->photo)
                                <img class="little-photo" src="{{ asset('storage/' . $user->photo) }}" />
                            @endif
                            <label for="photo" class="col-form-label">Фото</label>
                            <input id="photo" type="file" class="form-control{{ $errors->has('photo') ? ' is-invalid' : '' }}" name="photo">
                            @if ($errors->has('photo'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('photo') }}</strong></span>
                            @endif
                        </div>


                        <div class="form-group">
                            <label for="skype" class="col-form-label">Skype</label>
                            <textarea id="skype" class="form-control{{ $errors->has('skype') ? ' is-invalid' : '' }}" name="skype" rows="2" value="{{ old('skype', $user->skype) }}">{{ $user->skype }}</textarea>
                            @if ($errors->has('skype'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('skype') }}</strong></span>
                            @endif
                        </div>


                        <div class="form-group">
                            <label for="phone" class="col-form-label">Телефон</label>
                            <textarea id="phone" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" rows="2" value="{{ old('phone', $user->phone) }}">{{ $user->phone }}</textarea>
                            @if ($errors->has('phone'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('phone') }}</strong></span>
                            @endif
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Сотрудники
                    <a href="{{ route('home') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    @can('manage-users')
                        <p><a href="{{ route('user.create') }}" class="btn btn-success">Добавить сотрудника</a></p>
                    @endcan
                    <!-- USER SEARCH -->
                    <form action="?" method="get">
                        <input name="name" type="text" placeholder="Введите, что помните" value="{{request('name')}}">
                        <input type="submit" value="Найти сотрудника">
                    </form>
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Дата</th>
                            <th>Имя</th>
                            <th>E-mail</th>
                            <th>Статус</th>
                            <th>Фото</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->created_at}}</td>
                                <td><a href="{{ route('user.show', $user->id) }}">{{$user->last_name ?? '' }} {{ $user->first_name ?? '' }} {{ $user->second_name ?? '' }}</a></td>
                                <td>{{$user->email}}</td>
                                <td><span class="badge badge-primary">{{$statusesList[$user->status]}}</span></td>
                                <td>
                                    @if($user->photo)
                                        <img class="little-photo" src="{{ asset('storage/' . $user->photo) }}" />
                                    @endif
                                </td>
                                <td>
                                    @can('manage-users')
                                        <div class="d-flex flex-row">
                                            <a href="{{ route('user.show', $user) }}" class="btn btn-sm btn-primary mr-1">Детали</a>
                                            <form method="POST" action="{{ route('user.destroy', $user) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger mr-1">Удалить</button>
                                            </form>
                                        </div>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/show.blade.php
<?php use App\Entities\Candidate; ?>

@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                @if($user->isCandidate())
                    <a href="{{ route('candidate.index') }}" class="close">
                @else
                    <a href="{{ route('user.index') }}" class="close">
                @endif
                        <span aria-hidden="true">&times;</span>
                    </a>
                <h3>
                    {{ $userStatusesList[$user->status] }}
                    {{$user->first_name . ' ' . $user->last_name}}
                </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="@if ($user->isCandidate()) {{ 'col-md-5' }} @else {{ 'col-md-12' }} @endif">
                        <h4>Основные данные</h4>
                        <p>
                            @can('manage-users')
                                <div class="btn-group">
                                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Изменить статус пользователя
                                    </button>
                                    <div class="dropdown-menu">
                                        @foreach ($userStatusesList as $key => $value)
                                            @if ($user->status !== $key)
                                                <form method="POST" action="{{ route('user.changeStatus', ['user' => $user, 'status' => $key]) }}" class="mr-1">
                                                    @csrf
                                                    <button class="dropdown-item">{{ $value }}</button>
                                                </form>
                                            @endif
                                        @endforeach
                                    </div>
                                </div>
                            @endcan
                            @if (Gate::allows('edit-user-data', $user))
                                <a href="{{ route('user.edit', $user) }}" class="btn btn-success">Редактировать</a>
                            @endif
                        </p>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>Полное имя</th><td>{{ $user->first_name  . ' ' . $user->second_name . ' ' . $user->last_name }}</td>
                                </tr>
                                <tr>
                                    <th>Статус</th><td><span class="badge badge-{{Candidate::getBadgeColor($userStatusesList[$user->status])}}">{{ $userStatusesList[$user->status] }}</span></td>
                                </tr>
                                <tr>
                                    <th>Email</th><td>{{ $user->email }}</td>
                                </tr>
                                <tr>
                                    <th>Ссылки на соцсети</th><td>{{ $user->socials }}</td>
                                </tr>
                                <tr>
                                    <th>Образование</th><td>{{ $user->education }}</td>
                                </tr>
                                <tr>
                                    <th>Добавлен</th><td>{{ $user->created_at }}</td>
                                </tr>
                                <tr>
                                    <th>Фото</th>
                                    <td>
                                        @if ($user->photo)
                                            <img class="little-photo" src="{{ asset('storage/' . $user->photo) }}" />
                                        @endif
                                    </td>
                                </tr>
                            <tr>
                                <th>Телефон</th><td>{{ $user->phone }}</td>
                            </tr>
                            <tr><th>Skype</th><td>{{ $user->skype }}</td>

                            </tr>
                            </tbody>
                        </table>
                    </div>
                    @if ($user->isCandidate())
                        <div class="col-md-7">
                            <h4>История кандидатства</h4>
                            @can('manage-users')
                                <p><a href="{{ route('candidate.createCandidateRecord', $user) }}" class="btn btn-success">Добавить</a></p>
                            @endcan
                            <div class="accordion" id="accordionHistory">
                                @php($first = true)
                                @foreach ($user->candidatesHistory as $candidate)
                                <div class="card">
                                    <div class="card-header" id="{{ $candidate->id }}">
                                        <h5 class="mb-1">
                                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{ $candidate->id }}" aria-expanded="true" aria-controls="collapse{{ $candidate->id }}">
                                                {{ $candidate->created_at }}
                                            </button>
                                        </h5>
                                    </div>

                                    <div id="collapse{{ $candidate->id }}" class="collapse @if ($first) show @endif" aria-labelledby="{{ $candidate->id }}" data-parent="#accordionHistory">
                                        <div class="card-body">
                                            @if ($first)
                                                @can('manage-users')
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            Изменить статус кандидата
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            @foreach ($statusesList as $key => $value)
                                                                @if ($candidate->status !== $key)
                                                                    <form method="POST" action="{{ route('candidate.changeStatus', ['candidate' => $candidate, 'status' => $key]) }}" class="mr-1">
                                                                        @csrf
                                                                        <button class="dropdown-item">{{ $value }}</button>
                                                                    </form>
                                                                @endif
                                                            @endforeach
                                                        </div>
                                                    </div>
                                                    <a href="{{ route('candidate.edit', $candidate) }}" class="btn btn-success">Редактировать</a>
                                                @endcan
                                            @endif
                                            <table class="table table-bordered table-striped">
                                                <tbody>
                                                    <tr>
                                                        <th>Статус</th><td><span class="badge badge-{{\App\Entities\Candidate::getBadgeColor($statusesList[$candidate->status])}}">{{ $statusesList[$candidate->status] }}</span></td>
                                                    </tr>
                                                    <tr>
                                                        <th>Рекрутер</th><td>{{ $candidate->recruiter->last_name . ' ' . $candidate->recruiter->first_name }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Должность</th><td>{{ $candidate->position->title }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Зарплата</th><td>{{ $candidate->salary . ' ' . $candidate->currency->title }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Город</th><td>{{ $candidate->city->title }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Ссылка на резюме</th><td>{{ $candidate->cv_src }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Файл резюме</th>
                                                        <td>
                                                            @if ($candidate->cv_file)
                                                                <a target="_blank" href="{{ asset('storage/' . $candidate->cv_file) }}">скачать</a>
                                                            @endif
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th>Языки</th><td>{{ $candidate->languages }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Описание</th><td>{{ $candidate->description }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Последняя компания</th><td>{{ $candidate->last_company_id ? $candidate->lastCompany->title : ''}}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Заметки</th><td>{{ $candidate->notes }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Дата добавления</th><td>{{ $candidate->created_at }}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                @php($first = false)
                                @endforeach
                            </div>
                        </div>
                    @endif
                </div>

            </div>
        </div>
    </div>
</div>
@endsection